APPLICATION_MANAGER = "Application Manager"
BET_CONSUMER = "Bet Consumer"
BET_MANAGER = "Bet Manager"
ALL_GROUPS = [APPLICATION_MANAGER, BET_CONSUMER, BET_MANAGER]
MANAGER_GROUPS = [APPLICATION_MANAGER, BET_MANAGER] 
