# Generated by Django 3.1.3 on 2020-11-22 22:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('potential_earnings', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Ganancias potenciales')),
                ('won', models.BooleanField(null=True, verbose_name='Ganado')),
                ('creation_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modification_datetime', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Apuesta',
                'verbose_name_plural': 'Apuestas',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('rules', models.TextField(blank=True, null=True, verbose_name='Reglas')),
                ('creation_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modification_datetime', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('expiration_datetime', models.DateTimeField(verbose_name='Fecha de expiración')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('description', models.CharField(max_length=255, verbose_name='Descripción')),
                ('creation_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modification_datetime', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
            ],
            options={
                'verbose_name': 'Transacción',
                'verbose_name_plural': 'Transacciones',
            },
        ),
        migrations.CreateModel(
            name='Quota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probability', models.DecimalField(decimal_places=5, max_digits=6, verbose_name='Probabilidad')),
                ('creation_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modification_datetime', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('expiration_datetime', models.DateTimeField(verbose_name='Fecha de expiración')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bets.event', verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'Cuota',
                'verbose_name_plural': 'Cuotas',
            },
        ),
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Ganancia')),
                ('creation_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bets.bet', verbose_name='Apuesta')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Premio',
                'verbose_name_plural': 'Premios',
            },
        ),
        migrations.AddField(
            model_name='bet',
            name='quota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bets.quota', verbose_name='Cuota'),
        ),
        migrations.AddField(
            model_name='bet',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bets.transaction', verbose_name='Transacción'),
        ),
        migrations.AddField(
            model_name='bet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
