# Generated by Django 3.2.6 on 2021-08-06 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bets", "0003_quota_coeficient"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="affair",
            options={
                "verbose_name": "Asunto",
                "verbose_name_plural": "Asuntos",
            },
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={
                "verbose_name": "Etiqueta",
                "verbose_name_plural": "Etiquetas",
            },
        ),
    ]
