# Generated by Django 3.2.6 on 2021-08-06 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0004_auto_20210805_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='potential_earnings',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12, verbose_name='Ganancias potenciales'),
        ),
    ]
