name: Unit Tests

# on: [push, pull_request]
on: [push]

jobs:
  build:
#    name: Unit Tests
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_pwd
          POSTGRES_BD: test_db
        ports:
          - 5432/tcp
        options: --mount type=tmpfs,destination=/var/lib/postgresql/data --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest flake8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
#    - name: Run migrations
#      run: |
#        python manage.py migrate
    - name: Run tests
      run: |
        python manage.py test
      env:
        SYSTEM_ENV: GITHUB_WORKFLOW
